import OfflineBanner from "@/components/offline/offlineBanner";
import { useEffect, useMemo, useRef, useState } from "react";
import { Text, View, StyleSheet, Platform, RefreshControl, ScrollView, FlatList, Dimensions, NativeSyntheticEvent, NativeScrollEvent } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useTheme } from "@/themes/theme";
import API_BASE_URL from "@/config/config";
import { useFocusEffect } from '@react-navigation/native';
import { useCallback } from 'react';
import { Animated } from 'react-native';

import AntDesign from '@expo/vector-icons/AntDesign';
import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import AsyncStorage from "@react-native-async-storage/async-storage";
import TournamentView from "@/components/explore/tournamentView";
import useLocation from "@/hooks/useLocation";
import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { router } from "expo-router";

interface Tournament {
    id: string;
    tournament_name: string;
    date: string;
    category_image: string;
    distance: number;
    latitude: number | null;
    longitude: number | null;
    status: string | undefined;
}

export default function WelcomeScreen() {

    // Refresh control for pull-to-refresh
    const [refreshing, setRefreshing] = useState(false);
    const [hostedTournaments, setHostedTournaments] = useState<Tournament[]>([]);
    const [registeredTournaments, setRegisteredTournaments] = useState<Tournament[]>([]);
    const { latitude, longitude, error, getUserLocation } = useLocation();

    const fetchData = async () => {
        const userToken = await AsyncStorage.getItem("token");
        const userId = await AsyncStorage.getItem("userId");
        if (!userId || !userToken) return;

        const sortByDate = (arr: Tournament[]) => {
            const now = new Date().getTime();

            return arr.sort((a: Tournament, b: Tournament) => {
                const aDate = new Date(a.date).getTime();
                const bDate = new Date(b.date).getTime();

                const aInFuture = aDate >= now;
                const bInFuture = bDate >= now;

                if (aInFuture && !bInFuture) return -1; // a is in future, b past → a first
                if (!aInFuture && bInFuture) return 1;  // a is past, b future → b first

                // both in future or past → sort by date
                return aDate - bDate;
            });
        }; // this sort was generated by chatGPT-4o



        try {
            // Hosted tournaments
            const hostedResult = await fetch(`${API_BASE_URL}/users/${userId}/tournaments/owned`, {
                headers: { Authorization: `Bearer ${userToken}` },
            });

            const hostedData = await hostedResult.json();
            if (hostedResult.ok) {
                setHostedTournaments(sortByDate(hostedData));
            }


            // Registered tournaments
            const registeredResult = await fetch(`${API_BASE_URL}/users/${userId}/tournaments`, {
                headers: { Authorization: `Bearer ${userToken}` },
            });

            const registeredData = await registeredResult.json();
            if (registeredResult.ok) {
                setRegisteredTournaments(sortByDate(registeredData));
            }



        } catch (err) {
            console.warn("EventsScreen fetch error:", err);
            router.replace("/errorScreen");
        }
    };


    useEffect(() => {
        fetchData();
    }, []);

    useEffect(() => {
        getUserLocation();
    }, []);

    const onRefresh = async () => {
        setRefreshing(true);
        await fetchData();
        setRefreshing(false);
    };

    useFocusEffect(
        useCallback(() => {
            fetchData();
        }, [])
    );

    const screenWidth = Dimensions.get('window').width;
    const [activeIndex, setActiveIndex] = useState(0); // State to track the active index of the FlatList
    const isLargeScreen = useMemo(() => screenWidth >= 768, [screenWidth]);

    const theme = useTheme();
    const styles = useMemo(() => getStyles(theme, isLargeScreen), [theme]);

    const handleScroll = (event: NativeSyntheticEvent<NativeScrollEvent>) => {
        const index = Math.round(event.nativeEvent.contentOffset.x / screenWidth);
        setActiveIndex(index);
    }; // Function to handle the scroll event and update the active index

    const pulseAnim = useRef(new Animated.Value(1)).current;
    useEffect(() => {
        Animated.loop(
            Animated.sequence([
                Animated.timing(pulseAnim, {
                    toValue: 1.1,
                    duration: 1000,
                    useNativeDriver: true,
                }),
                Animated.timing(pulseAnim, {
                    toValue: 1,
                    duration: 1000,
                    useNativeDriver: true,
                }),
            ])
        ).start();
    }, []);

    const chunkArray = <T,>(array: T[], size: number): T[][] => {
        const result: T[][] = [];
        for (let i = 0; i < array.length; i += size) {
            result.push(array.slice(i, i + size));
        }
        return result;
    };

    const hostedPairs = isLargeScreen
        ? chunkArray(hostedTournaments, 2)
        : hostedTournaments.map((t) => [t]);

    return (
        <SafeAreaView style={styles.safeArea} >

            <OfflineBanner />
            <ScrollView
                showsVerticalScrollIndicator={false}
                contentContainerStyle={{ paddingBottom: 40 }}
                refreshControl={
                    <RefreshControl refreshing={refreshing} onRefresh={onRefresh} />
                }
            >

                {/* Hosted tournaments */}
                <View>
                    <View style={styles.mainTitle}>
                        <MaterialCommunityIcons style={styles.icon} name="hammer-wrench" size={28} color={theme.text} />
                        <Text style={styles.title}>Hosted Tournaments</Text>
                    </View>

                    <Text style={styles.sectionTitle}>You are hosting these tournaments: </Text>
                    {hostedTournaments.length > 0 ? (
                        <FlatList
                            data={hostedPairs}
                            keyExtractor={(_, index) => `hosted-page-${index}`}
                            horizontal
                            pagingEnabled
                            showsHorizontalScrollIndicator={false}
                            onScroll={handleScroll}
                            scrollEventThrottle={16}
                            renderItem={({ item: pair }) => (
                                <View style={styles.hostedRow}>
                                    {pair.map((item) => (
                                        <View key={item.id} style={styles.hostedCard}>
                                            <TournamentView
                                                title={item.tournament_name}
                                                date={item.date}
                                                imageUrl={{ uri: `${API_BASE_URL}/category/images/${item.category_image}` }}
                                                tournamentId={item.id}
                                                lat={null}
                                                lon={null}
                                                userLat={null}
                                                userLon={null}
                                                defaultDistance={item.distance}
                                                type="owned"
                                                status={item.status}
                                            />
                                        </View>
                                    ))}
                                </View>
                            )}
                        />

                    ) : (
                        <View style={styles.container}>
                            <MaterialIcons name="help-center" size={40} color={theme.text} />
                            <Text style={styles.message}>You didn't host a tournament yet</Text>
                        </View>
                    )}
                    <View style={styles.dotsContainer}>
                        {hostedPairs.map((_, index) => (
                            <Text
                                key={index}
                                style={[
                                    styles.dot,
                                    index === activeIndex ? styles.activeDot : styles.inactiveDot,
                                ]}
                            >
                                ●
                            </Text>
                        ))}
                    </View>
                </View>
                {/* Happening Now tournaments */}
                {registeredTournaments.filter(item => item.status === 'Ongoing').length > 0 && (
                    <View>
                        <View style={styles.mainTitle}>
                            <Animated.View style={{ transform: [{ scale: pulseAnim }] }}>
                                <MaterialIcons name="live-tv" style={styles.liveIcon} size={25} />
                            </Animated.View>
                            <Text style={styles.liveTitle}>Happening Now</Text>
                        </View>
                        <View>
                            <FlatList
                                data={registeredTournaments.filter(item => item.status === 'Ongoing')}
                                keyExtractor={(item) => item.id}
                                numColumns={isLargeScreen ? 2 : 1}
                                columnWrapperStyle={isLargeScreen ? styles.registeredColumnWrapper : undefined}
                                contentContainerStyle={styles.registeredList}
                                scrollEnabled={false}
                                renderItem={({ item }) => (
                                    <View style={styles.registeredCardWrapper}>
                                        <TournamentView
                                            title={item.tournament_name}
                                            date={item.date}
                                            imageUrl={{ uri: `${API_BASE_URL}/category/images/${item.category_image}` }}
                                            tournamentId={item.id}
                                            lat={null}
                                            lon={null}
                                            userLat={null}
                                            userLon={null}
                                            defaultDistance={item.distance}
                                            type="ticket"
                                            ticketId={item.id}
                                        />
                                    </View>
                                )}
                            />


                        </View>

                    </View>
                )}


                {/* Upcomming tournaments */}
                <View>
                    <View style={styles.mainTitle}>
                        <AntDesign name="Trophy" style={styles.icon} size={25} color={theme.text} />
                        <Text style={styles.title}>Upcoming events</Text>
                    </View>
                    <View>
                        {registeredTournaments.filter(item => item.status !== 'Ongoing').length > 0 ? (
                            <FlatList
                                data={registeredTournaments.filter(item => item.status !== 'Ongoing')}
                                keyExtractor={(item) => item.id}
                                numColumns={isLargeScreen ? 2 : 1}
                                columnWrapperStyle={isLargeScreen ? styles.registeredColumnWrapper : undefined}
                                contentContainerStyle={styles.registeredList}
                                scrollEnabled={false}
                                renderItem={({ item }) => (
                                    <View style={styles.registeredCardWrapper}>
                                        <TournamentView
                                            title={item.tournament_name}
                                            date={item.date}
                                            imageUrl={{ uri: `${API_BASE_URL}/category/images/${item.category_image}` }}
                                            tournamentId={item.id}
                                            lat={null}
                                            lon={null}
                                            userLat={null}
                                            userLon={null}
                                            defaultDistance={item.distance}
                                            type="ticket"
                                            ticketId={item.id}
                                        />
                                    </View>
                                )}
                            />

                        ) : (
                            <Text style={styles.emptyText}>You will see your upcoming tournaments here.</Text>
                        )}

                    </View>

                </View>


            </ScrollView>

        </SafeAreaView>
    );
}


const getStyles = (theme: ReturnType<typeof useTheme>, isLargeScreen: boolean) => StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: theme.background,
        paddingTop: Platform.OS === 'ios' ? 0 : 40,
    },
    mainTitle: {
        flexDirection: 'row',
        textAlignVertical: 'center',
        marginTop: 20,
        marginLeft: 25,
    },
    title: {
        fontSize: 25,
        fontWeight: 'bold',
        marginBottom: 25,
        color: theme.text,
    },
    liveTitle: {
        fontSize: 25,
        fontWeight: 'bold',
        marginBottom: 25,
        color: theme.liveColor,
    },
    icon: {
        marginTop: 2,
        marginRight: 10,
        color: theme.text,
    },
    liveIcon: {
        marginTop: 2,
        marginRight: 10,
        color: theme.liveColor,
    },
    sectionTitle: {
        fontSize: 12,
        fontWeight: "bold",
        margin: 20,
        color: theme.text,
    },
    emptyText: {
        padding: 20,
        fontSize: 14,
        color: theme.mutedText,
        fontStyle: "italic",
        marginRight: 20,
        marginBottom: 10,
        marginLeft: 20,
        backgroundColor: theme.card,
        borderRadius: 10,
    },
    dotsContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 12,
    },
    dot: {
        fontSize: 10,
        marginHorizontal: 4,
        color: theme.dotInactive,
    },
    activeDot: {
        color: theme.dotActive,
    },
    inactiveDot: {
        color: theme.dotInactive,
    },
    container: {
        backgroundColor: theme.card,
        marginHorizontal: 20,
        padding: 16,
        borderRadius: 12,
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        marginBottom: 12,
        height: 100,
    },
    message: {
        color: theme.text,
        fontSize: 14,
        fontWeight: 700,
    },
    hostedRow: {
        width: Dimensions.get('window').width,
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
    },
    hostedCard: {
        flex: isLargeScreen ? undefined : 1,
        width: isLargeScreen
            ? (Dimensions.get('window').width - 48) / 2
            : undefined,
        marginHorizontal: isLargeScreen ? 8 : 0,
    },
    registeredList: {
        paddingHorizontal: 16,
        paddingBottom: 20,
    },
    registeredColumnWrapper: {
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    registeredCardWrapper: {
        marginHorizontal: isLargeScreen ? 8 : 0,
        width: isLargeScreen
            ? (Dimensions.get('window').width - 48) / 2 // 2 cards with spacing
            : undefined,     // full width on small screens
        height: 220,
    },

});
