import { View, Text, StyleSheet } from 'react-native';
import { useTheme } from '@/themes/theme';

interface LeaderboardEntry {
    position: number;
    name: string;
}

interface Props {
    data: LeaderboardEntry[];
}

export default function Leaderboard({ data }: Props) {
    const theme = useTheme();
    const styles = getStyles(theme);

    return (
        <View style={styles.wrapper}>
            <Text style={styles.title}>Leaderboard</Text>
            {data.length === 0 ? (
                <Text style={styles.empty}>Leaderboard was not published yet</Text>
            ) : (
                data.map((entry) => (
                    <View key={entry.position} style={styles.row}>
                        <Text style={styles.position}>{ordinal(entry.position)}</Text>
                        <Text style={styles.name}>{entry.name}</Text>
                    </View>
                ))
            )}
        </View>
    );
}

const ordinal = (n: number) => { // Generated by OpenAI
    const s = ['th', 'st', 'nd', 'rd'];
    const v = n % 100;
    return n + (s[(v - 20) % 10] || s[v] || s[0]);
};

const getStyles = (theme: ReturnType<typeof useTheme>) =>
    StyleSheet.create({
        wrapper: {
            marginBottom: 24,
        },
        title: {
            fontSize: 18,
            fontWeight: 'bold',
            color: theme.text,
            marginBottom: 12,
        },
        row: {
            flexDirection: 'row',
            alignItems: 'center',
            padding: 10,
            backgroundColor: theme.card,
            marginBottom: 6,
            borderRadius: 8,
        },
        position: {
            width: 40,
            fontWeight: '600',
            color: theme.text,
        },
        name: {
            flex: 1,
            color: theme.text,
        },
        empty: {
            fontSize: 14,
            color: '#999',
            fontStyle: 'italic',
        },
    });
